# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: boat.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'boat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nboat.proto\x12\x04\x62oat\"/\n\x08Position\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"|\n\x04\x42oat\x12\x1a\n\x12\x62\x61ttery_percentage\x18\x01 \x01(\x02\x12 \n\x08position\x18\x02 \x01(\x0b\x32\x0e.boat.Position\x12#\n\x0f\x61utonomous_mode\x18\x03 \x01(\x0e\x32\n.boat.Mode\x12\x11\n\tdirection\x18\x04 \x01(\x02*\"\n\x04Mode\x12\n\n\x06MANUAL\x10\x00\x12\x0e\n\nAUTONOMOUS\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODE']._serialized_start=195
  _globals['_MODE']._serialized_end=229
  _globals['_POSITION']._serialized_start=20
  _globals['_POSITION']._serialized_end=67
  _globals['_BOAT']._serialized_start=69
  _globals['_BOAT']._serialized_end=193
# @@protoc_insertion_point(module_scope)
